name: Publish Nightly Releases

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: zlls/github-actions/npm-version-nightly@master
        env:
          OPENINC_NPM_TOKEN: ${{secrets.npm_token}}
      - run: npm ci
        env:
          OPENINC_NPM_TOKEN: ${{secrets.npm_token}}
      - run: npm run build --if-present
        env:
          OPENINC_NPM_TOKEN: ${{secrets.npm_token}}
      - run: npm publish --tag nightly
        env:
          OPENINC_NPM_TOKEN: ${{secrets.npm_token}}
